version: '3'

services:
  app:
    build: ./app
    tty: true
    depends_on:
      - db
    volumes:
      - ./app:/go/app
    ports:
      - "3000:3000"
  db:
    restart: always
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: deploy
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db/data:/var/lib/postgresql/data:z
